Repository manvipaliwal/todolist, pull requests merged in 2022-10, with the labels that each got.

#3 accept kar rajudiii
  style.css
Labels: hacktoberfest, hacktoberfest2022

#4 update file
  style.css
Labels: hacktoberfest, hatoberfest-accepted

#5 updated
  style.css
Labels: hacktoberfest2022, hatoberfest-accepted
